local_costmap:
    global_frame: map

    static_map: false
    rolling_window: true
    width: 4.0
    height: 4.0
    resolution: 0.01

    update_frequency: 10.0
    publish_frequency: 10.0


    plugins: 
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: local_inflation_layer,         type: "costmap_2d::InflationLayer"}
        - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
