base_local_planner: teb_local_planner/TebLocalPlannerROS
TebLocalPlannerROS:
  enable_homotopy_class_planning: false

  max_vel_x: 0.4
  max_vel_x_backwards: 0.1
  max_vel_theta: 0.3
  acc_lim_x: 0.2
  acc_lim_theta: 0.1

  weight_kinematics_forward_drive: 10.0
  min_obstacle_dist: 0.5

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1